directories:
  - name: "Herold"
    start_urls:
      - "https://www.herold.at/gelbe-seiten/wien/elektriker/"
      - "https://www.herold.at/gelbe-seiten/wien/friseur/"
      - "https://www.herold.at/gelbe-seiten/wien/installateur/"
      - "https://www.herold.at/gelbe-seiten/restaurant/"
    pagination:
      type: "next_link"
      selector: "a[rel='next']"
    rules:
      include_text_hints: ["Website", "Web", "Homepage", "Webseite"]
    max_pages: 30
    delay_seconds: 1.0
